// <auto-generated />
using E_commerce__website_final_project_.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace E_commerce__website_final_project_.Migrations
{
    [DbContext(typeof(projectcontext))]
    [Migration("20240802060419_second")]
    partial class second
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("E_commerce__website_final_project_.Models.admin", b =>
                {
                    b.Property<string>("a_e_mail")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("a_password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("a_e_mail");

                    b.ToTable("admins");

                    b.HasData(
                        new
                        {
                            a_e_mail = "a@gmail.com",
                            a_password = "1234"
                        },
                        new
                        {
                            a_e_mail = "b@gmail.com",
                            a_password = "5678"
                        });
                });

            modelBuilder.Entity("E_commerce__website_final_project_.Models.customer", b =>
                {
                    b.Property<string>("c_e_mail")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("c_address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("c_password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("c_e_mail");

                    b.ToTable("customers");
                });

            modelBuilder.Entity("E_commerce__website_final_project_.Models.product", b =>
                {
                    b.Property<int>("p_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("p_id"));

                    b.Property<string>("p_name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("p_pic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("p_price")
                        .HasColumnType("int");

                    b.Property<int>("p_qty")
                        .HasColumnType("int");

                    b.HasKey("p_id");

                    b.ToTable("products");
                });
#pragma warning restore 612, 618
        }
    }
}
